# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='WebPlayer.Tutorial')),
            ],
        ),
        migrations.RenameField(
            model_name='step',
            old_name='timestamp',
            new_name='startTime',
        ),
        migrations.RemoveField(
            model_name='step',
            name='action',
        ),
        migrations.RemoveField(
            model_name='step',
            name='content',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='qty',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='WebPlayer.Step'),
        ),
    ]
